### PR TITLE
Make toArray conversion recursive

### PR DESCRIPTION
**Pull request by shadowhand**
Fetching a flat array from a complex structure is often valuable for
data transmission.

### CODE REVIEW

**Comment by shadowhand** [comment]
@elazar does this seem like a good idea?

**Comment by elazar** [comment]
@shadowhand I don't see why not. Seems convenient. In the vast majority of use cases, there should be a termination condition for the recursion. So, looks good to me. :+1:

**Comment by shadowhand** [comment]
@elazar I rebased this to add PullApprove. Can you reup, please?

**Comment by elazar** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/equip/structure/pull-request/1/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=equip/structure)

**Comment by shadowhand** [comment]
Thanks!

**Pull request merged**
